name: proyecto-chispita

services:
  db:
    image: postgres:15-alpine
    container_name: chispita_postgres
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - chispita_pgdata:/var/lib/postgresql/data
    networks:
      - proxy-network

  backend:
    build: ./backend
    container_name: chispita_backend
    restart: unless-stopped
    env_file: .env
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - proxy-network

  frontend:
    build: ./frontend
    container_name: chispita_frontend
    restart: unless-stopped
    networks:
      - proxy-network

volumes:
  chispita_pgdata:

networks:
  proxy-network:
    external: true